// Code generated by Icestudio 0.11.0-rc2

`default_nettype none

//---- Top entity
module main (
 input vf96519,
 input vclk,
 output vbabc7e,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 assign vbabc7e = w31;
 assign w38 = vf96519;
 assign w41 = vclk;
 assign w42 = vclk;
 assign w43 = vclk;
 assign w44 = vclk;
 assign w45 = vclk;
 assign w46 = vclk;
 assign w47 = vclk;
 assign w48 = vclk;
 assign w49 = vclk;
 assign w50 = vclk;
 assign w51 = vclk;
 assign w52 = vclk;
 assign w53 = vclk;
 assign w54 = vclk;
 assign w55 = vclk;
 assign w56 = vclk;
 assign w57 = vclk;
 assign w58 = vclk;
 assign w59 = vclk;
 assign w60 = vclk;
 assign w61 = vclk;
 assign w62 = vclk;
 assign w63 = vclk;
 assign w64 = vclk;
 assign w65 = vclk;
 assign w66 = vclk;
 assign w67 = vclk;
 assign w68 = vclk;
 assign w69 = vclk;
 assign w70 = vclk;
 assign w71 = vclk;
 assign w72 = vclk;
 assign w32 = w0;
 assign w33 = w4;
 assign w35 = w27;
 assign w37 = w5;
 assign w42 = w41;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w41;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w41;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w47 = w41;
 assign w47 = w42;
 assign w47 = w43;
 assign w47 = w44;
 assign w47 = w45;
 assign w47 = w46;
 assign w48 = w41;
 assign w48 = w42;
 assign w48 = w43;
 assign w48 = w44;
 assign w48 = w45;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w41;
 assign w49 = w42;
 assign w49 = w43;
 assign w49 = w44;
 assign w49 = w45;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w41;
 assign w50 = w42;
 assign w50 = w43;
 assign w50 = w44;
 assign w50 = w45;
 assign w50 = w46;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w41;
 assign w51 = w42;
 assign w51 = w43;
 assign w51 = w44;
 assign w51 = w45;
 assign w51 = w46;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w41;
 assign w52 = w42;
 assign w52 = w43;
 assign w52 = w44;
 assign w52 = w45;
 assign w52 = w46;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w41;
 assign w53 = w42;
 assign w53 = w43;
 assign w53 = w44;
 assign w53 = w45;
 assign w53 = w46;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 assign w54 = w41;
 assign w54 = w42;
 assign w54 = w43;
 assign w54 = w44;
 assign w54 = w45;
 assign w54 = w46;
 assign w54 = w47;
 assign w54 = w48;
 assign w54 = w49;
 assign w54 = w50;
 assign w54 = w51;
 assign w54 = w52;
 assign w54 = w53;
 assign w55 = w41;
 assign w55 = w42;
 assign w55 = w43;
 assign w55 = w44;
 assign w55 = w45;
 assign w55 = w46;
 assign w55 = w47;
 assign w55 = w48;
 assign w55 = w49;
 assign w55 = w50;
 assign w55 = w51;
 assign w55 = w52;
 assign w55 = w53;
 assign w55 = w54;
 assign w56 = w41;
 assign w56 = w42;
 assign w56 = w43;
 assign w56 = w44;
 assign w56 = w45;
 assign w56 = w46;
 assign w56 = w47;
 assign w56 = w48;
 assign w56 = w49;
 assign w56 = w50;
 assign w56 = w51;
 assign w56 = w52;
 assign w56 = w53;
 assign w56 = w54;
 assign w56 = w55;
 assign w57 = w41;
 assign w57 = w42;
 assign w57 = w43;
 assign w57 = w44;
 assign w57 = w45;
 assign w57 = w46;
 assign w57 = w47;
 assign w57 = w48;
 assign w57 = w49;
 assign w57 = w50;
 assign w57 = w51;
 assign w57 = w52;
 assign w57 = w53;
 assign w57 = w54;
 assign w57 = w55;
 assign w57 = w56;
 assign w58 = w41;
 assign w58 = w42;
 assign w58 = w43;
 assign w58 = w44;
 assign w58 = w45;
 assign w58 = w46;
 assign w58 = w47;
 assign w58 = w48;
 assign w58 = w49;
 assign w58 = w50;
 assign w58 = w51;
 assign w58 = w52;
 assign w58 = w53;
 assign w58 = w54;
 assign w58 = w55;
 assign w58 = w56;
 assign w58 = w57;
 assign w59 = w41;
 assign w59 = w42;
 assign w59 = w43;
 assign w59 = w44;
 assign w59 = w45;
 assign w59 = w46;
 assign w59 = w47;
 assign w59 = w48;
 assign w59 = w49;
 assign w59 = w50;
 assign w59 = w51;
 assign w59 = w52;
 assign w59 = w53;
 assign w59 = w54;
 assign w59 = w55;
 assign w59 = w56;
 assign w59 = w57;
 assign w59 = w58;
 assign w60 = w41;
 assign w60 = w42;
 assign w60 = w43;
 assign w60 = w44;
 assign w60 = w45;
 assign w60 = w46;
 assign w60 = w47;
 assign w60 = w48;
 assign w60 = w49;
 assign w60 = w50;
 assign w60 = w51;
 assign w60 = w52;
 assign w60 = w53;
 assign w60 = w54;
 assign w60 = w55;
 assign w60 = w56;
 assign w60 = w57;
 assign w60 = w58;
 assign w60 = w59;
 assign w61 = w41;
 assign w61 = w42;
 assign w61 = w43;
 assign w61 = w44;
 assign w61 = w45;
 assign w61 = w46;
 assign w61 = w47;
 assign w61 = w48;
 assign w61 = w49;
 assign w61 = w50;
 assign w61 = w51;
 assign w61 = w52;
 assign w61 = w53;
 assign w61 = w54;
 assign w61 = w55;
 assign w61 = w56;
 assign w61 = w57;
 assign w61 = w58;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w41;
 assign w62 = w42;
 assign w62 = w43;
 assign w62 = w44;
 assign w62 = w45;
 assign w62 = w46;
 assign w62 = w47;
 assign w62 = w48;
 assign w62 = w49;
 assign w62 = w50;
 assign w62 = w51;
 assign w62 = w52;
 assign w62 = w53;
 assign w62 = w54;
 assign w62 = w55;
 assign w62 = w56;
 assign w62 = w57;
 assign w62 = w58;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w63 = w41;
 assign w63 = w42;
 assign w63 = w43;
 assign w63 = w44;
 assign w63 = w45;
 assign w63 = w46;
 assign w63 = w47;
 assign w63 = w48;
 assign w63 = w49;
 assign w63 = w50;
 assign w63 = w51;
 assign w63 = w52;
 assign w63 = w53;
 assign w63 = w54;
 assign w63 = w55;
 assign w63 = w56;
 assign w63 = w57;
 assign w63 = w58;
 assign w63 = w59;
 assign w63 = w60;
 assign w63 = w61;
 assign w63 = w62;
 assign w64 = w41;
 assign w64 = w42;
 assign w64 = w43;
 assign w64 = w44;
 assign w64 = w45;
 assign w64 = w46;
 assign w64 = w47;
 assign w64 = w48;
 assign w64 = w49;
 assign w64 = w50;
 assign w64 = w51;
 assign w64 = w52;
 assign w64 = w53;
 assign w64 = w54;
 assign w64 = w55;
 assign w64 = w56;
 assign w64 = w57;
 assign w64 = w58;
 assign w64 = w59;
 assign w64 = w60;
 assign w64 = w61;
 assign w64 = w62;
 assign w64 = w63;
 assign w65 = w41;
 assign w65 = w42;
 assign w65 = w43;
 assign w65 = w44;
 assign w65 = w45;
 assign w65 = w46;
 assign w65 = w47;
 assign w65 = w48;
 assign w65 = w49;
 assign w65 = w50;
 assign w65 = w51;
 assign w65 = w52;
 assign w65 = w53;
 assign w65 = w54;
 assign w65 = w55;
 assign w65 = w56;
 assign w65 = w57;
 assign w65 = w58;
 assign w65 = w59;
 assign w65 = w60;
 assign w65 = w61;
 assign w65 = w62;
 assign w65 = w63;
 assign w65 = w64;
 assign w66 = w41;
 assign w66 = w42;
 assign w66 = w43;
 assign w66 = w44;
 assign w66 = w45;
 assign w66 = w46;
 assign w66 = w47;
 assign w66 = w48;
 assign w66 = w49;
 assign w66 = w50;
 assign w66 = w51;
 assign w66 = w52;
 assign w66 = w53;
 assign w66 = w54;
 assign w66 = w55;
 assign w66 = w56;
 assign w66 = w57;
 assign w66 = w58;
 assign w66 = w59;
 assign w66 = w60;
 assign w66 = w61;
 assign w66 = w62;
 assign w66 = w63;
 assign w66 = w64;
 assign w66 = w65;
 assign w67 = w41;
 assign w67 = w42;
 assign w67 = w43;
 assign w67 = w44;
 assign w67 = w45;
 assign w67 = w46;
 assign w67 = w47;
 assign w67 = w48;
 assign w67 = w49;
 assign w67 = w50;
 assign w67 = w51;
 assign w67 = w52;
 assign w67 = w53;
 assign w67 = w54;
 assign w67 = w55;
 assign w67 = w56;
 assign w67 = w57;
 assign w67 = w58;
 assign w67 = w59;
 assign w67 = w60;
 assign w67 = w61;
 assign w67 = w62;
 assign w67 = w63;
 assign w67 = w64;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w41;
 assign w68 = w42;
 assign w68 = w43;
 assign w68 = w44;
 assign w68 = w45;
 assign w68 = w46;
 assign w68 = w47;
 assign w68 = w48;
 assign w68 = w49;
 assign w68 = w50;
 assign w68 = w51;
 assign w68 = w52;
 assign w68 = w53;
 assign w68 = w54;
 assign w68 = w55;
 assign w68 = w56;
 assign w68 = w57;
 assign w68 = w58;
 assign w68 = w59;
 assign w68 = w60;
 assign w68 = w61;
 assign w68 = w62;
 assign w68 = w63;
 assign w68 = w64;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w41;
 assign w69 = w42;
 assign w69 = w43;
 assign w69 = w44;
 assign w69 = w45;
 assign w69 = w46;
 assign w69 = w47;
 assign w69 = w48;
 assign w69 = w49;
 assign w69 = w50;
 assign w69 = w51;
 assign w69 = w52;
 assign w69 = w53;
 assign w69 = w54;
 assign w69 = w55;
 assign w69 = w56;
 assign w69 = w57;
 assign w69 = w58;
 assign w69 = w59;
 assign w69 = w60;
 assign w69 = w61;
 assign w69 = w62;
 assign w69 = w63;
 assign w69 = w64;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w41;
 assign w70 = w42;
 assign w70 = w43;
 assign w70 = w44;
 assign w70 = w45;
 assign w70 = w46;
 assign w70 = w47;
 assign w70 = w48;
 assign w70 = w49;
 assign w70 = w50;
 assign w70 = w51;
 assign w70 = w52;
 assign w70 = w53;
 assign w70 = w54;
 assign w70 = w55;
 assign w70 = w56;
 assign w70 = w57;
 assign w70 = w58;
 assign w70 = w59;
 assign w70 = w60;
 assign w70 = w61;
 assign w70 = w62;
 assign w70 = w63;
 assign w70 = w64;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w41;
 assign w71 = w42;
 assign w71 = w43;
 assign w71 = w44;
 assign w71 = w45;
 assign w71 = w46;
 assign w71 = w47;
 assign w71 = w48;
 assign w71 = w49;
 assign w71 = w50;
 assign w71 = w51;
 assign w71 = w52;
 assign w71 = w53;
 assign w71 = w54;
 assign w71 = w55;
 assign w71 = w56;
 assign w71 = w57;
 assign w71 = w58;
 assign w71 = w59;
 assign w71 = w60;
 assign w71 = w61;
 assign w71 = w62;
 assign w71 = w63;
 assign w71 = w64;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w72 = w41;
 assign w72 = w42;
 assign w72 = w43;
 assign w72 = w44;
 assign w72 = w45;
 assign w72 = w46;
 assign w72 = w47;
 assign w72 = w48;
 assign w72 = w49;
 assign w72 = w50;
 assign w72 = w51;
 assign w72 = w52;
 assign w72 = w53;
 assign w72 = w54;
 assign w72 = w55;
 assign w72 = w56;
 assign w72 = w57;
 assign w72 = w58;
 assign w72 = w59;
 assign w72 = w60;
 assign w72 = w61;
 assign w72 = w62;
 assign w72 = w63;
 assign w72 = w64;
 assign w72 = w65;
 assign w72 = w66;
 assign w72 = w67;
 assign w72 = w68;
 assign w72 = w69;
 assign w72 = w70;
 assign w72 = w71;
 v8b89a5 vccf7c3 (
  .vc24d9f(w0),
  .vef4cea(w40),
  .vb55943(w41)
 );
 v8b89a5 v21f563 (
  .vef4cea(w0),
  .vc24d9f(w1),
  .vb55943(w42)
 );
 v8b89a5 ve58120 (
  .vef4cea(w1),
  .vc24d9f(w2),
  .vb55943(w43)
 );
 v8b89a5 v6e8779 (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w44)
 );
 v8b89a5 vd3c4d9 (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w45)
 );
 v8b89a5 vb29fce (
  .vef4cea(w4),
  .vc24d9f(w5),
  .vb55943(w46)
 );
 v8b89a5 v669f7b (
  .vef4cea(w5),
  .vc24d9f(w6),
  .vb55943(w47)
 );
 v8b89a5 v1a8a09 (
  .vef4cea(w6),
  .vc24d9f(w28),
  .vb55943(w48)
 );
 v8b89a5 v8e2367 (
  .vc24d9f(w7),
  .vef4cea(w28),
  .vb55943(w49)
 );
 v8b89a5 v3b0614 (
  .vef4cea(w7),
  .vc24d9f(w8),
  .vb55943(w50)
 );
 v8b89a5 v950b89 (
  .vef4cea(w8),
  .vc24d9f(w9),
  .vb55943(w51)
 );
 v8b89a5 v5e7589 (
  .vef4cea(w9),
  .vc24d9f(w10),
  .vb55943(w52)
 );
 v8b89a5 v4e0165 (
  .vef4cea(w10),
  .vc24d9f(w11),
  .vb55943(w53)
 );
 v8b89a5 v848321 (
  .vef4cea(w11),
  .vc24d9f(w12),
  .vb55943(w54)
 );
 v8b89a5 vc12576 (
  .vef4cea(w12),
  .vc24d9f(w13),
  .vb55943(w55)
 );
 v8b89a5 v3cf4c0 (
  .vef4cea(w13),
  .vc24d9f(w29),
  .vb55943(w56)
 );
 v8b89a5 v9f977d (
  .vc24d9f(w14),
  .vef4cea(w29),
  .vb55943(w57)
 );
 v8b89a5 ved7bf7 (
  .vef4cea(w14),
  .vc24d9f(w15),
  .vb55943(w58)
 );
 v8b89a5 v0b3242 (
  .vef4cea(w15),
  .vc24d9f(w16),
  .vb55943(w59)
 );
 v8b89a5 v3863e6 (
  .vef4cea(w16),
  .vc24d9f(w17),
  .vb55943(w60)
 );
 v8b89a5 v52c37f (
  .vef4cea(w17),
  .vc24d9f(w18),
  .vb55943(w61)
 );
 v8b89a5 v567ed0 (
  .vef4cea(w18),
  .vc24d9f(w19),
  .vb55943(w62)
 );
 v8b89a5 vbe79fe (
  .vef4cea(w19),
  .vc24d9f(w20),
  .vb55943(w63)
 );
 v8b89a5 v272e0c (
  .vef4cea(w20),
  .vc24d9f(w30),
  .vb55943(w64)
 );
 v8b89a5 v010ad6 (
  .vc24d9f(w21),
  .vef4cea(w30),
  .vb55943(w65)
 );
 v8b89a5 v6d8419 (
  .vef4cea(w21),
  .vc24d9f(w22),
  .vb55943(w66)
 );
 v8b89a5 v652e57 (
  .vef4cea(w22),
  .vc24d9f(w23),
  .vb55943(w67)
 );
 v8b89a5 v21994c (
  .vef4cea(w23),
  .vc24d9f(w24),
  .vb55943(w68)
 );
 v8b89a5 v626e29 (
  .vef4cea(w24),
  .vc24d9f(w25),
  .vb55943(w69)
 );
 v8b89a5 v0cbd94 (
  .vef4cea(w25),
  .vc24d9f(w26),
  .vb55943(w70)
 );
 v8b89a5 v298633 (
  .vef4cea(w26),
  .vc24d9f(w27),
  .vb55943(w71)
 );
 v8b89a5 vf067be (
  .vef4cea(w27),
  .vc24d9f(w31),
  .vb55943(w72)
 );
 ve9ceb2 vf8ab67 (
  .v0e28cb(w32),
  .v3ca442(w33),
  .vcbab45(w34)
 );
 ve9ceb2 vc9750d (
  .v0e28cb(w34),
  .v3ca442(w36),
  .vcbab45(w39)
 );
 ve9ceb2 v0dd625 (
  .v3ca442(w35),
  .vcbab45(w36),
  .v0e28cb(w37)
 );
 v528969 v77631f (
  .v3ca442(w38),
  .v0e28cb(w39),
  .vcbab45(w40)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module v8b89a5 (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v8b89a5_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v8b89a5_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module ve9ceb2 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 ve9ceb2_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR logic gate
//---------------------------------------------------

module ve9ceb2_vf4938a (
 input a,
 input b,
 output c
);
 // XOR logic gate
 
 assign c = a ^ b;
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR logic gate
//---------------------------------------------------

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
