// Code generated by Icestudio 0.11.0-rc2

`default_nettype none

//---- Top entity
module main #(
 parameter v9ac438 = 25
) (
 input vbf6b1c,
 input vclk,
 output ve243bb,
 output v363ffd,
 output v993960,
 output v2cee8e
);
 localparam p0 = v9ac438;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign v2cee8e = w5;
 assign v993960 = w6;
 assign v363ffd = w7;
 assign ve243bb = w8;
 assign w9 = vbf6b1c;
 assign w13 = vclk;
 assign w2 = w1;
 assign w3 = w1;
 assign w3 = w2;
 assign w4 = w1;
 assign w4 = w2;
 assign w4 = w3;
 assign w10 = w8;
 assign w11 = w7;
 assign w12 = w6;
 v6a5074 #(
  .v100e1b(p0)
 ) v3f79b7 (
  .v2efea4(w1),
  .v0daa9e(w13)
 );
 v8b89a5 vb4139b (
  .vb55943(w1),
  .vc24d9f(w8),
  .vef4cea(w9)
 );
 v8b89a5 v98d3e8 (
  .vb55943(w2),
  .vc24d9f(w7),
  .vef4cea(w10)
 );
 v8b89a5 v705b2d (
  .vb55943(w3),
  .vc24d9f(w6),
  .vef4cea(w11)
 );
 v8b89a5 v7c64d3 (
  .vb55943(w4),
  .vc24d9f(w5),
  .vef4cea(w12)
 );
endmodule

//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v8b89a5 (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v8b89a5_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v8b89a5_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
